name: PiiWii Timeline Extractor Windows 1.0.1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: echo "Build temporarily paused while 1.0.1 sources are updated."
